export const eventData=[
[

{
               artiste: "Invesco QQQ Atlanta Gridiron Classic - Georgia Tech vs Georgia",

        img: "https://github.com/centurystone619/Img/blob/main/IMG_0360.jpeg?raw=true",
        sec: "123",
        row: "25",
        seat: "7",
        date: "Fri, Nov 28, 2025",
        time: "3:30 PM",
        state: "Atlanta, GA",
        venue: "Mercedes-Benz Stadium",
        type: "Standard Ticket",
        eventData: {
          month: "Nov",
          day: "28",
          year: "",
          time: "Fri - 3:30",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['7','8','9','10'],
          desc: "Mobile",
          GA: "",
          color: "",
          gate: "",
          btnColor: "",
          sell: "y",
          trnsfer: "y",
            addOns:"",
            walletColor:'green',
          sportSec:'y',
          ticketAction:'m'
        }
      },
      {
        artiste: "Invesco QQQ Atlanta Gridiron Classic - Georgia Tech vs Georgia",
        img: "https://github.com/centurystone619/Img/blob/main/IMG_0360.jpeg?raw=true",
        sec: "123",
        row: "25",
        seat: "8",
        date: "Fri, Nov 28, 2025",
        time: "TBA",
        state: "Tennessee",
        venue: "Neyland Stadium",
        type: "Standard Ticket",
        eventData: {
          month: "Nov",
          day: "01",
          year: "",
          time: "Sat - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "",
          venueMap: "",
          gate: "",
          btnColor: "",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
      },

      {
        artiste: "Vol Football V Vanderbilt",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "21",
        date: "Sat, Nov 01, 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "01",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
        {
        artiste: "Vol Football V Vanderbilt",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "22",
        date: "Sat, Nov 20 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "30",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
  ],
  
]