export const eventData=[
[

{
               artiste: "SEC Football Championship",

        img: "https://github.com/centurystone619/Img/blob/main/IMG_0547.jpeg?raw=true",
        sec: "132",
        row: "37",
        seat: "6",
        date: "Sat, Dec 06, 2025",
        time: "4:00 PM",
        state: "Atlanta, GA",
        venue: "Mercedes-Benz Stadium",
        type: "Verified Resale Ticket",
        eventData: {
          month: "Dec",
          day: "06",
          year: "",
          time: "Sat - 3:30",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['6','7','8','9'],
          desc: "Mobile",
          GA: "",
          color: "",
          gate: "",
          btnColor: "",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
            walletColor:'green',
          sportSec:'',
          ticketAction:''
        }
      },
      {
        artiste: "SEC Football Championship",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "132",
        row: "37",
        seat: "7",
        date: "Sat, Dec 06, 2025",
        time: "4:00 PM",
        state: "Atlanta, GA",
        venue: "Mercedes-Benz Stadium",
        type: "Verified Resale Ticket",
        eventData: {
          month: "Dec",
          day: "06",
          year: "",
          time: "Sat - 4:00",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "Mobile",
          GA: "",
          color: "",
          venueMap: "",
          gate: "",
          btnColor: "",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
      },

      {
        artiste: "SEC Football Championship",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "21",
        date: "Sat, Dec 01, 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Mercedes-Benz Stadium",
        type: "",
        eventData: {
          month: "Dec",
          day: "01",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "Mobile",
          GA: "",
          color: "",
          venueMap: "",
          gate: "",
          btnColor: "",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
        {
        artiste: "Vol Football V Oklahoma",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "22",
        date: "Sat, Dec 20 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Mercedes-Benz Stadium",
        type: "",
        eventData: {
          month: "Dec",
          day: "30",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "Mobile",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
  ],
  
]