export const eventData=[
[

{
               artiste: "Vol Football vs. Vanderbilt",

        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "19",
        date: "Sat, Nov 29, 2025",
        time: "TBA",
        state: "Knoxville, TN",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "29",
          year: "",
          time: "Sat - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['19','20','21','22'],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"",
            walletColor:'green',
          sportSec:'y',
          ticketAction:'m'
        }
      },
      {
        artiste: "Vol Football V Vanderbilt",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "20",
        date: "Sat, Nov 29, 2025",
        time: "TBA",
        state: "Tennessee",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "29",
          year: "",
          time: "Sat - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
      },

      {
        artiste: "Vol Football V Vanderbilt",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "21",
        date: "Sat, Nov 29, 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "29",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
        {
        artiste: "Vol Football V Vanderbilt",
        img: "https://github.com/centurystone619/Img/blob/main/Ojpg.PNG?raw=true",
        sec: "Y6",
        row: "48",
        seat: "22",
        date: "Sat, Nov 29 2025",
        time: "TBA",
        state: "South Carolina",
        venue: "Neyland Stadium",
        type: "",
        eventData: {
          month: "Nov",
          day: "29",
          year: "",
          time: "Wee - TBA",
          region: "",
          orderNo: ""
        },
        transfers: {
          sec: "",
          row: "",
          seats: ['',''],
          desc: "NonPremium Gates",
          GA: "",
          color: "#ff8202",
          venueMap: "",
          gate: "",
          btnColor: "#ff8202",
          sell: "y",
          trnsfer: "y",
            addOns:"y",
           sportSec:'y',
        }
        },
  ],
  
]