export const data = [
  {
    id: 1,
    name: "Search All",
    price: "",
    date: "",
    fbSearch: "https://www.facebook.com/search/top?q=looking%20ticket",
    fbEvent: "",
    twitter: "https://x.com/search?q=looking%20%20ticket&src=typed_query&f=top",
  },
  {
    id: 50,
    name: "Sammy Virji(BRIXTON)",
    price: "25 euro",
    date: "Feb 1",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Sat, Feb 1",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Feb",
      day: "1",
      time: "Sat - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-6432/UK",
    },
  },
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Sat, Feb 1",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Feb",
      day: "1",
      time: "Sat - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Sat, Feb 1",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Feb",
      day: "1",
      time: "Sat - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["", "", ""],
  ticketId: ["1", "2", "3"],
  desc: "STALLS GENERAL ADMISSION - SRO",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "General Admission",
  venueMap: "",
  color: "",
};
`,
  },
  {
    id: 50,
    name: "Sammy Virji(BRIXTON)",
    price: "25 euro",
    date: "Jan 31",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Fri, Jan 31",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-6432/UK",
    },
  },
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Fri, Jan 31",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
  {
    artiste: "Sammy Virji",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/351/e919839d-e30c-4a07-a2e8-7cc77c8e1351_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "",
    seat: "",
    date: "Fri, Jan 31",
    time: "9:00 PM",
    state: "London, UK",
    venue: "O2 Academy Brixton",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 21:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["", "", ""],
  ticketId: ["1", "2", "3"],
  desc: "STALLS GENERAL ADMISSION - SRO",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "General Admission",
  venueMap: "",
  color: "",
};
`,
  },

  {
    id: 50,
    name: "Dan and Phil (MANCHESTER)",
    price: "",
    date: "Jan 29",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "15",
    date: "Wed, Jan 29",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "29",
      time: "Wed - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-7854/UK",
    },
  },
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "16",
    date: "Wed, Jan 29",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "29",
      time: "Wed - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "17",
    date: "Wed, Jan 29",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "29",
      time: "Wed - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["15", "16", "17"],
  ticketId: ["", "", ""],
  desc: "GROUND LEVEL",
  gate: "MAIN ENTRANCE",
  showBar: "Y",
  GA: "",
  venueMap: "",
  color: "",
};
`,
  },
  {
    id: 50,
    name: "Dan and Phil (MANCHESTER)",
    price: "",
    date: "Jan 30",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "15",
    date: "Thu, Jan 30",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "30",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-7854/UK",
    },
  },
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "16",
    date: "Thu, Jan 30",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "30",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
  {
    artiste: "Dan and Phil - TERRIBLE INFLUENCE",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "B",
    seat: "17",
    date: "Thu, Jan 30",
    time: "7:00 PM",
    state: "Manchester, UK",
    venue: "O2 Apollo Manchester",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "30",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["15", "16", "17"],
  ticketId: ["", "", ""],
  desc: "GROUND LEVEL",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "",
  venueMap: "",
  color: "",
};
`,
  },
  {
    id: 50,
    name: "Dan & Phil(BELFAST)",
    price: "",
    date: " Feb 2",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: ` export const data = [
    {
      artiste: "Dan & Phil - Terrible Influence",
      img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
      sec: "BLOCKA",
      row: "9",
      seat: "7",
      date: "Sun, Feb 2",
      time: "7:00 PM",
      state: "Belfast, UK",
      venue: "Waterfront Hall Auditorium",
      type: "Standard Ticket",
      eventData: {
        month: "Feb",
        day: "2",
        time: "Sun - 19:00",
        year: "2025",
        region: "UK",
        orderNo: "42-7854/UK",
      },
    },
    {
      artiste: "Dan & Phil - Terrible Influence",
      img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
      sec: "BLOCKA",
      row: "9",
      seat: "8",
      date: "Sun, Feb 2",
      time: "7:00 PM",
      state: "Belfast, UK",
      venue: "Waterfront Hall Auditorium",
      type: "Standard Ticket",
      eventData: {
        month: "Feb",
        day: "2",
        time: "Sun - 19:00",
        year: "2025",
        region: "UK",
        orderNo: "42-XXXX/UK",
      },
    },
    {
      artiste: "Dan & Phil - Terrible Influence",
      img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
      sec: "BLOCKA",
      row: "9",
      seat: "9",
      date: "Sun, Feb 2",
      time: "7:00 PM",
      state: "Belfast, UK",
      venue: "Waterfront Hall Auditorium",
      type: "Standard Ticket",
      eventData: {
        month: "Feb",
        day: "2",
        time: "Sun - 19:00",
        year: "2025",
        region: "UK",
        orderNo: "42-XXXX/UK",
      },
    },
  ];
  
  export const transfers = {
    sec: "",
    row: "",
    seats: ["7", "8", "9"],
    ticketId: ["", "", ""],
    desc: "BLOCK A",
    gate: "MAIN ENTRANCE",
    showBar: "",
    GA: "",
    venueMap: "",
    color: "",
  }`,
  },
  {
    id: 50,
    name: "Dan and Phil (DUBLIN)",
    price: "",
    date: "Jan 31",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Dan and Phil: Terrible Influence",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "CC",
    seat: "24",
    date: "Fri, Jan 31",
    time: "7:00 PM",
    state: "Dublin, Ireland",
    venue: "The Convention Centre Dublin",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 19:00",
      year: "2025",
      region: "Ireland",
      orderNo: "42-7854/IE",
    },
  },
  {
    artiste: "Dan and Phil: Terrible Influence",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "CC",
    seat: "25",
    date: "Fri, Jan 31",
    time: "7:00 PM",
    state: "Dublin, Ireland",
    venue: "The Convention Centre Dublin",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 19:00",
      year: "2025",
      region: "Ireland",
      orderNo: "42-XXXX/IE",
    },
  },
  {
    artiste: "Dan and Phil: Terrible Influence",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/b92/56a3533f-2ec5-4b47-b9fc-3b41a9384b92_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STALLS",
    row: "CC",
    seat: "26",
    date: "Fri, Jan 31",
    time: "7:00 PM",
    state: "Dublin, Ireland",
    venue: "The Convention Centre Dublin",
    type: "Standard Ticket",
    eventData: {
      month: "Jan",
      day: "31",
      time: "Fri - 19:00",
      year: "2025",
      region: "Ireland",
      orderNo: "42-XXXX/IE",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["24", "25", "26"],
  ticketId: ["", "", ""],
  desc: "GROUND LEVEL",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "",
  venueMap: "",
  color: "",
};
`,
  },
  {
    id: 50,
    name: "Megan Moroney (TN)",
    price: "",
    date: "Apr 11",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "3A",
    row: "3",
    seat: "5",
    date: "Fri, Apr 11",
    time: "8:00 PM",
    state: "Knoxville, TN, USA",
    venue: "Knoxville Civic Coliseum",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "11",
      time: "Fri - 20:00",
      year: "2025",
      region: "",
      orderNo: "42-5743/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "3A",
    row: "3",
    seat: "6",
    date: "Fri, Apr 11",
    time: "8:00 PM",
    state: "Knoxville, TN, USA",
    venue: "Knoxville Civic Coliseum",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "11",
      time: "Fri - 20:00",
      year: "2025",
      region: "USA",
      orderNo: "42-XXXX/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "3A",
    row: "3",
    seat: "7",
    date: "Fri, Apr 11",
    time: "8:00 PM",
    state: "Knoxville, TN, USA",
    venue: "Knoxville Civic Coliseum",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "11",
      time: "Fri - 20:00",
      year: "2025",
      region: "USA",
      orderNo: "42-XXXX/US",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["5", "6", "7"],
  ticketId: ["", "", ""],
  desc: "GROUND FLOOR",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "",
  venueMap: "",
  color: "",
};
`,
  },
  {
    id: 50,
    name: "Megan Moroney(AL)",
    price: "",
    date: "Apr 03",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dam/a/764/ee04147d-9608-4146-b315-ef52893e3764_EVENT_DETAIL_PAGE_16_9.jpg", 
    sec: "111",
    row: "B",
    seat: "8",
    date: "Thu, Apr 03",
    time: "8:00 PM",
    state: "Huntsville, AL, USA",
    venue: "Orion Amphitheater",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "03",
      time: "Thu - 20:00",
      year: "2025",
      region: "",
      orderNo: "42-XXXX/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dam/a/764/ee04147d-9608-4146-b315-ef52893e3764_EVENT_DETAIL_PAGE_16_9.jpg", 
    sec: "111",
    row: "B",
    seat: "9",
    date: "Thu, Apr 03",
    time: "8:00 PM",
    state: "Huntsville, AL, USA",
    venue: "Orion Amphitheater",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "03",
      time: "Thu - 20:00",
      year: "2025",
      region: "",
      orderNo: "42-XXXX/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dam/a/764/ee04147d-9608-4146-b315-ef52893e3764_EVENT_DETAIL_PAGE_16_9.jpg", 
    sec: "111",
    row: "B",
    seat: "10",
    date: "Thu, Apr 03",
    time: "8:00 PM",
    state: "Huntsville, AL, USA",
    venue: "Orion Amphitheater",
    type: "Standard Ticket",
    eventData: {
      month: "Apr",
      day: "03",
      time: "Thu - 20:00",
      year: "2025",
      region: "USA",
      orderNo: "42-XXXX/US",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["8", "9", "10"],
  ticketId: ["", "", ""],
  desc: "GROUND FLOOR",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "",
  venueMap: "",
  color: "",
};
`,
  },

  {
    id: 50,
    name: "Megan Moroney - Am I Okay? Tour",
    price: "",
    date: "Mar 22",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "FLOOR",
    row: "",
    seat: "",
    date: "Sat, Mar 22",
    time: "7:00 PM",
    state: "USA",
    venue: "History",
    type: "Verified Resale Ticket",
    eventData: {
      month: "Mar",
      day: "22",
      time: "Sat - 19:00",
      year: "2025",
      region: "USA",
      orderNo: "42-5743/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "FLOOR",
    row: "",
    seat: "",
    date: "Sat, Mar 22",
    time: "7:00 PM",
    state: "USA",
venue: "History",
    type: "Verified Resale Ticket",
    eventData: {
      month: "Mar",
      day: "22",
      time: "Sat - 19:00",
      year: "2025",
      region: "USA",
      orderNo: "42-XXXX/US",
    },
  },
  {
    artiste: "Megan Moroney - Am I Okay? Tour",
    img: "https://s1.ticketm.net/dbimages/531743a.jpg",
    sec: "FLOOR",
    row: "",
    seat: "",
    date: "Sat, Mar 22",
    time: "7:00 PM",
    state: "USA",
    venue: "History",
    type: "Verified Resale Ticket",
    eventData: {
      month: "Mar",
      day: "22",
      time: "Sat - 19:00",
      year: "2025",
      region: "USA",
      orderNo: "42-XXXX/US",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["", "", ""],
  ticketId: ["1", "2", "3"],
  desc: "FLOOR - SRO",
  gate: "ALL EVENT ACCESS",
  showBar: "",
  GA: "GENERAL ADMISSION",
  venueMap: "",
  color: "",
};
`,
  },

  {
    id: 50,
    name: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    price: "",
    date: " Mar 8",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    img: "https://s1.ticketm.net/dam/a/e89/0077a6e2-a82d-4d67-bd68-c47aa3212e89_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "112",
    row: "A",
    seat: "42",
    date: "Sat, Mar 8",
    time: "6:30 PM",
    state: "London, UK",
    venue: "The O2",
    type: "Artist Presale",
    eventData: {
      month: "Mar",
      day: "8",
      time: "Sat - 18:30",
      year: "2025",
      region: "UK",
      orderNo: "42-7642/UK",
    },
  },
  {
    artiste: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    img: "https://s1.ticketm.net/dam/a/e89/0077a6e2-a82d-4d67-bd68-c47aa3212e89_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "112",
    row: "A",
    seat: "43",
    date: "Sat, Mar 8",
    time: "6:30 PM",
    state: "London, UK",
    venue: "The O2",
    type: "Artist Presale",
    eventData: {
      month: "Mar",
      day: "8",
      time: "Sat - 18:30",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
  {
    artiste: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    img: "https://s1.ticketm.net/dam/a/e89/0077a6e2-a82d-4d67-bd68-c47aa3212e89_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "112",
    row: "A",
    seat: "44",
    date: "Sat, Mar 8",
    time: "6:30 PM",
    state: "London, UK",
    venue: "The O2",
    type: "Artist Presale",
    eventData: {
      month: "Mar",
      day: "8",
      time: "Sat - 18:30",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["42", "43", "44"],
  ticketId: ["", "", ""],
  desc: "LOWER LEVEL SEATING",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "",
  venueMap: "https://tixel.com/maps/51.5009,0.0063",
  color: "",
};`,
  },
  {
    id: 50,
    name: "Oasis (Cardiff)",
    price: "",
    date: "Jul 4",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Oasis",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/236/107e678f-4a91-44e7-8849-9f6fb5c35236_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "L6",
    row: "2",
    seat: "17",
    date: "Fri, Jul 4",
    time: "5:00 PM",
    state: "Cardiff, Wales, UK",
    venue: "Principality Stadium",
    type: "General Sale Ticket",
    eventData: {
      month: "Jul",
      day: "4",
      time: "Fri - 17:00",
      year: "2025",
      region: "UK",
      orderNo: "42-8854/UK",
    },
  },
  {
    artiste: "Oasis",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/236/107e678f-4a91-44e7-8849-9f6fb5c35236_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "L6",
    row: "2",
    seat: "18",
    date: "Fri, Jul 4",
    time: "5:00 PM",
    state: "Cardiff, Wales, UK",
    venue: "Principality Stadium",
    type: "General Sale Ticket",
    eventData: {
      month: "Jul",
      day: "4",
      time: "Fri - 17:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },

{
    artiste: "Oasis",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/236/107e678f-4a91-44e7-8849-9f6fb5c35236_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "L6",
    row: "2",
    seat: "19",
    date: "Fri, Jul 4",
    time: "5:00 PM",
    state: "Cardiff, Wales, UK",
    venue: "Principality Stadium",
    type: "General Sale Ticket",
    eventData: {
      month: "Jul",
      day: "4",
      time: "Fri - 17:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  }

];

export const transfers = {
  sec: "",
  row: "",
  seats: ["17", "18", "19"],
  ticketId: ["", ""],
  desc: "LOWER LEVEL",
  gate: "GATE 3",
  showBar: "",
  GA: "",
  venueMap: "  https://tixel.com/maps/51.4795,-3.1807",
  color: "",
  view2: "1"
};`,
  },
  {
    id: 50,
    name: "Olly Murs (plymouth)",
    price: "",
    date: "Apr 24",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "Olly Murs",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/689/60bb4d8d-af36-4386-aa2e-5af1d0660689_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STANDING ",
    row: "",
    seat: "",
    date: "Thu, Apr 24",
    time: "7:00 PM",
    state: "Plymouth, UK",
    venue: "Plymouth Pavilions",
    type: "Standing Ticket ",
    eventData: {
      month: "Apr",
      day: "24",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-5544/UK",
    },
  },
  {
    artiste: "Olly Murs",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/689/60bb4d8d-af36-4386-aa2e-5af1d0660689_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STANDING ",
    row: "",
    seat: "",
    date: "Thu, Apr 24",
    time: "7:00 PM",
    state: "Plymouth, UK",
    venue: "Plymouth Pavilions",
    type: "Standing Ticket ",
    eventData: {
      month: "Apr",
      day: "24",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },

  {
    artiste: "Olly Murs",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/689/60bb4d8d-af36-4386-aa2e-5af1d0660689_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STANDING ",
    row: "",
    seat: "",
    date: "Thu, Apr 24",
    time: "7:00 PM",
    state: "Plymouth, UK",
    venue: "Plymouth Pavilions",
    type: "Standing Ticket ",
    eventData: {
      month: "Apr",
      day: "24",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },

  {
    artiste: "Olly Murs",
    img: "https://media.ticketmaster.co.uk/tm/en-gb/dam/a/689/60bb4d8d-af36-4386-aa2e-5af1d0660689_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "STANDING ",
    row: "",
    seat: "",
    date: "Thu, Apr 24",
    time: "7:00 PM",
    state: "Plymouth, UK",
    venue: "Plymouth Pavilions",
    type: "Standing Ticket ",
    eventData: {
      month: "Apr",
      day: "24",
      time: "Thu - 19:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["", "", ""],
  ticketId: ["1", "2", "3"],
  desc: "STALLS - SRO",
  gate: "MAIN ENTRANCE",
  showBar: "",
  GA: "General Admission",
  venueMap: " https://tixel.com/maps/50.367901,-4.1501",
  color: "",
  view2: "1",
};
`,
  },

   {
    id: 50,
    name: "American Express Presents BST Hyde Park - Zach Bryan",
    price: "",
    date: "Jun 28",
    fbSearch: "",
    fbEvent: "",
    fbGroup: "",
    twitter: "",
    detail: `export const data = [
  {
    artiste: "American Express Presents BST Hyde Park - Zach Bryan",
    img: "https://s1.ticketm.net/dam/a/6a3/70eaea85-e3c5-4975-924e-ebde32e266a3_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "LGA",
    row: "",
    seat: "",
    date: "Sat, Jun 28",
    time: "2:00 PM",
    state: "London, UK",
    venue: "Hyde Park",
    type: "Verified Resale Ticket",
    eventData: {
      month: "Jun",
      day: "28",
      time: "Sat - 14:00",
      year: "2025",
      region: "UK",
      orderNo: "42-7854/UK",
    },
  },
  {
    artiste: "American Express Presents BST Hyde Park - Zach Bryan",
    img: "https://s1.ticketm.net/dam/a/6a3/70eaea85-e3c5-4975-924e-ebde32e266a3_EVENT_DETAIL_PAGE_16_9.jpg",
    sec: "LGA",
    row: "",
    seat: "",
    date: "Sat, Jun 28",
    time: "2:00 PM",
    state: "London, UK",
    venue: "Hyde Park",
    type: "Verified Resale Ticket",
    eventData: {
      month: "Jun",
      day: "28",
      time: "Sat - 14:00",
      year: "2025",
      region: "UK",
      orderNo: "42-XXXX/UK",
    },
  },
];

export const transfers = {
  sec: "",
  row: "",
  seats: ["", ""],
  ticketId: ["1", "2"],
  desc: "STANDING - TIER 3",
  gate: "NORTH ENTRANCE",
  showBar: "",
  GA: "General Admission ",
  venueMap: "https://tixel.com/maps/51.507301,-0.1657",
  color: "",
};`,
  },

  {
    id:50,
    name:"Eagles - Live at Sphere",
   price:"" ,
   date:" Feb 14",
   fbSearch:"",
   fbEvent:"",
   fbGroup:"",
   twitter:"",
    detail:` [

    {
      artiste: "Eagles - Live at Sphere",
      img: "https://s1.ticketm.net/dam/a/71d/ad124f24-1532-4dae-937f-d32c3340471d_EVENT_DETAIL_PAGE_16_9.jpg", 
      sec: "103",
      row: "25",
      seat: "3",
      date: "Fri, Feb 14",
      time: "8:30pm",
      state: "Nevada",
      venue: "Sphere, Las Vegas",
      type: "Official Platinum",
      eventData: {
        month: "Feb",
        day: "14",
        year: "2025",
        time: "Fri - 20:30",
        region: "",
        orderNo: ""
      },
      transfers: {
        sec: "",
        row: "",
        seats: ["3", "4"],
        desc: "OBSTRUCTED VIEW",
        GA: "",
        color: "",
        venueMap: "",
        gate: "",
        btnColor: "",
        sell: "y",
        trnsfer: "y"
      }
    },
    {
      artiste: "Eagles - Live at Sphere",
      img: "https://s1.ticketm.net/dam/a/71d/ad124f24-1532-4dae-937f-d32c3340471d_EVENT_DETAIL_PAGE_16_9.jpg", 
      sec: "103",
      row: "25",
      seat: "4",
      date: "Fri, Feb 14",
      time: "8:30pm",
      state: "Nevada",
      venue: "Sphere, Las Vegas",
      type: "Official Platinum",
      eventData: {
        month: "Feb",
        day: "14",
        year: "2025",
        time: "Fri - 20:30",
        region: "",
        orderNo: ""
      },
      transfers: {
        sec: "",
        row: "",
        seats: ["", ""],
        desc: "OBSTRUCTED VIEW",
        GA: "",
        color: "",
        venueMap: "",
        gate: "",
        btnColor: "",
        sell: "y",
        trnsfer: "y"
      }
    },
  
  ]`
  },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
  // {
  //   id:50,
  //   name:"",
  //  price:"" ,
  //  date:"",
  //  fbSearch:"",
  //  fbEvent:"",
  //  fbGroup:"",
  //  twitter:"",
  //   detail:``
  // },
];
